apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  annotations:
    {{ toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.global.hosts.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab
                port:
                  number: {{ .Values.service.port }}