apiVersion: v1
kind: Service
metadata:
  name: gitlab
  annotations:
    kubernetes.io/description: "Service for GitLab with NodePort"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
      protocol: TCP
      name: http
    - port: 30088
      targetPort: 30088
      nodePort: 30088
      protocol: TCP
      name: http-alt
  selector:
    app: gitlab