apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-nextcloud-config
data:
  config.php: |
    <?php
    $CONFIG = array (
      'datadirectory' => '{{ .Values.nextcloud.datadir }}',
      'dbtype' => '{{ .Values.externalDatabase.type }}',
      'dbname' => '{{ .Values.externalDatabase.database }}',
      'dbhost' => '{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}',
      'dbuser' => '{{ .Values.externalDatabase.user }}',
      'dbpassword' => '{{ .Values.externalDatabase.password }}',
      'overwrite.cli.url' => 'http://nextcloud-nextcloud.default.svc.cluster.local',
      'installed' => false,
      'memcache.local' => '\\OC\\Memcache\\Redis',
      'memcache.locking' => '\\OC\\Memcache\\Redis',
      'redis' => array(
        'host' => '{{ .Values.redis.host }}',
        'port' => {{ .Values.redis.port }},
        'password' => '{{ .Values.redis.password }}',
      ),
    );
  redis-session.ini: |
    session.save_handler = redis
    session.save_path = "tcp://{{ .Values.redis.host }}:{{ .Values.redis.port }}?auth={{ .Values.redis.password }}"