apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nextcloud
  labels:
    app: {{ .Release.Name }}-nextcloud
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nextcloud
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nextcloud
    spec:
      containers:
        - name: nextcloud
          image: {{ .Values.nextcloud.image }}
          ports:
            - containerPort: {{ .Values.nextcloud.port }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.externalDatabase.host }}
            - name: POSTGRES_PORT
              value: "{{ .Values.externalDatabase.port }}"
            - name: POSTGRES_DB
              value: {{ .Values.externalDatabase.database }}
            - name: POSTGRES_USER
              value: {{ .Values.externalDatabase.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.externalDatabase.password }}
            - name: NEXTCLOUD_ADMIN_USER
              value: {{ .Values.nextcloud.adminUser }}
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: {{ .Values.nextcloud.adminPassword }}
            - name: NEXTCLOUD_DATA_DIR
              value: {{ .Values.nextcloud.datadir }}
        {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
        {{- end }}
          volumeMounts:
            - name: nextcloud-data
              mountPath: {{ .Values.nextcloud.datadir }}
            - name: config
              mountPath: /var/www/html/config/config.php
              subPath: config.php
          securityContext:
            runAsUser: 33
            fsGroup: 33
      {{- if .Values.exporter.enabled }}
        - name: nextcloud-exporter
          image: {{ .Values.exporter.image }}
          ports:
            - containerPort: {{ .Values.exporter.port }}
          env:
            - name: NEXTCLOUD_SERVER
              value: {{ .Values.exporter.server | quote }}
            - name: NEXTCLOUD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-nextcloud-secrets
                  key: auth-token
        {{- if .Values.exporter.auth.username }}
            - name: NEXTCLOUD_USERNAME
              value: {{ .Values.exporter.auth.username | quote }}
            - name: NEXTCLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-nextcloud-secrets
                  key: auth-password
        {{- end }}
            - name: NEXTCLOUD_TIMEOUT
              value: {{ .Values.exporter.timeout | quote }}
        {{- if .Values.exporter.tlsSkipVerify }}
            - name: NEXTCLOUD_TLS_SKIP_VERIFY
              value: "true"
        {{- end }}
        {{- if .Values.exporter.enableApps }}
            - name: NEXTCLOUD_INFO_APPS
              value: "true"
        {{- end }}
        {{- if .Values.exporter.enableUpdates }}
            - name: NEXTCLOUD_INFO_UPDATE
              value: "true"
        {{- end }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      {{- end }}
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-nextcloud-pvc
        - name: config
          configMap:
            name: {{ .Release.Name }}-nextcloud-config