apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nextcloud-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}