apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nextcloud-secrets
type: Opaque
data:
  auth-token: {{ .Values.exporter.auth.token | b64enc | quote }}
  {{- if .Values.exporter.auth.username }}
  auth-password: {{ .Values.exporter.auth.password | b64enc | quote }}
  {{- end }}