apiVersion: v1
kind: Service
metadata:
  name: nextcloud-nextcloud
  labels:
    app: nextcloud-nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.nextcloud.port }}
      targetPort: {{ .Values.nextcloud.port }}
      nodePort: {{ .Values.nextcloud.nodePort }}
    - name: metrics
      port: {{ .Values.exporter.port }}
      targetPort: {{ .Values.exporter.port }}
      nodePort: {{ .Values.exporter.nodePort }}
  selector:
    app: nextcloud-nextcloud