global:
  minio:
    enabled: true
    host: "{{ .Release.Name }}-minio"
    port: 9000
    accessKey:
      secret: "{{ .Release.Name }}-minio-secret"
      key: "accessKey"
    secretKey:
      secret: "{{ .Release.Name }}-minio-secret"
      key: "secretKey"