apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.rootPassword }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.database }}
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mongodb.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.mongodb.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb