apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  type: NodePort
  ports:
  - name: mongodb
    port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
    nodePort: {{ .Values.mongodb.nodePort }}
  selector:
    app: {{ .Release.Name }}-mongodb