apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-config
data:
  server.properties: |
    process.roles=broker,controller
    node.id={{ .Values.nodeId }}
    controller.quorum.voters={{ .Values.controllerQuorumVoters }}
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://{{ .Release.Name }}-kafka-{{ .Values.nodeId }}.{{ .Release.Name }}-kafka-headless.{{ .Release.Namespace }}.svc.cluster.local:9092
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    inter.broker.listener.name=PLAINTEXT
    num.partitions=1
    default.replication.factor=3
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    log.retention.hours=168
    log.retention.bytes=-1
    cluster.id={{ .Values.clusterId }}