apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  clusterId: {{ .Values.cluster.id | quote }}
  log4j2.properties: |
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
  server.properties: |
    broker.id=0
    num.partitions=3
    default.replication.factor=3
    auto.create.topics.enable=true
    delete.topic.enable=true
    log.retention.hours=168
    log.segment.bytes=1073741824
    num.io.threads=8
    num.network.threads=3