apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  clusterId: {{ .Values.cluster.id | quote }}
  log4j2.properties: |
    status = WARN
    name = KafkaServer
    appenders = console
    appender.console.type = Console
    appender.console.name = STDOUT
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    rootLogger = ERROR, stdout
    appender.stdout = org.apache.log4j.ConsoleAppender
    appender.stdout.Target = System.out
    appender.stdout.layout = org.apache.log4j.PatternLayout
    appender.stdout.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    logger.my.test.logger=INFO
    rootLogger.level = INFO
    rootLogger.appenderRefs = console
    rootLogger.appenderRef.console.ref = STDOUT
    logger.kafka.name = kafka
    logger.kafka.level = INFO
    logger.kafka.additivity = false
    logger.kafka.appenderRefs = console
    logger.kafka.appenderRef.console.ref = STDOUT