apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  clusterId: {{ .Values.cluster.id | quote }}
  kafka.properties: |
    name=stdout
    appender=org.apache.log4j.ConsoleAppender
    layout=org.apache.log4j.PatternLayout
    layout.conversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    rootLogger.level=INFO
    rootLogger.appenderNames=stdout