apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.zookeeper.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size }}