apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}