apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: {{ .Values.persistence.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}