apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ .Release.Name }}-kafka-{{ .Values.nodeId }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  selector:
    matchLabels:
      app: kafka
      nodeId: "{{ .Values.nodeId }}"