apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - name: broker
      port: {{ .Values.ports.broker }}
      targetPort: {{ .Values.ports.broker }}
      nodePort: {{ .Values.ports.external.nodePort }}
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: broker
      port: {{ .Values.ports.broker }}
      targetPort: {{ .Values.ports.broker }}
    - name: controller
      port: {{ .Values.ports.controller }}
      targetPort: {{ .Values.ports.controller }}
  selector:
    app: kafka