apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
  ports:
    - name: broker
      port: {{ .Values.port.broker }}
      targetPort: {{ .Values.port.broker }}
      nodePort: {{ .Values.nodePort }}
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: broker
      port: {{ .Values.port.broker }}
      targetPort: {{ .Values.port.broker }}
    - name: controller
      port: {{ .Values.port.controller }}
      targetPort: {{ .Values.port.controller }}
  selector:
    app: kafka