apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  type: NodePort
  ports:
  - port: {{ .Values.zookeeper.port }}
    targetPort: {{ .Values.zookeeper.port }}
    nodePort: {{ .Values.zookeeper.nodePort }}
  selector:
    app: {{ .Release.Name }}-zookeeper