apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-headless
  labels:
    app: {{ .Release.Name }}-kafka
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: plaintext
  - port: 9093
    name: controller
  selector:
    app: {{ .Release.Name }}-kafka
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  ports:
  - port: 9092
    name: plaintext
  selector:
    app: {{ .Release.Name }}-kafka