apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  type: NodePort
  ports:
  - port: {{ .Values.kafka.port }}
    targetPort: {{ .Values.kafka.port }}
    nodePort: {{ .Values.kafka.nodePort }}
  selector:
    app: {{ .Release.Name }}-kafka