apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-headless
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: plaintext
      targetPort: 9092
    - port: 9093
      name: controller
      targetPort: 9093
  selector:
    app: {{ .Release.Name }}-kafka