apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-zookeeper-pv
spec:
  capacity:
    storage: {{ .Values.zookeeper.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.zookeeper.persistence.storageClass }}
  local:
    path: /mnt/disks/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-main