image:
  repository: hashicorp/vault
  tag: "1.15"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8200
server:
  ha:
    enabled: false
  storage:
    size: 10Gi
injector:
  enabled: true
resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"