mariadb:
  image: mariadb:10.6
  port: 3306
  nodePort: 30010
  rootPassword: mariadb-secret
  database: mydb
persistence:
  enabled: true
  storageClass: local-storage
  accessModes:
    - ReadWriteOnce
  size: 8Gi