apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: postgres-password
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      {{- if .Values.metrics.enabled }}
      - name: metrics-exporter
        image: {{ .Values.metrics.image }}
        ports:
        - containerPort: {{ .Values.metrics.port }}
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@localhost:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}?sslmode=disable"
      {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgres-pvc
      {{- else }}
      - name: postgres-data
        emptyDir: {}
      {{- end }}