{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
type: Opaque
data:
  password: {{ .Values.postgres.password | default "supersecret" | b64enc | quote }}
{{- end }}