apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc }}
  pgadmin-password: {{ .Values.pgadmin.password | b64enc }}