apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.pgadmin.port }}
    targetPort: {{ .Values.pgadmin.port }}
    nodePort: {{ .Values.service.pgadminNodePort }}
  selector:
    app: pgadmin