   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: {{ include "redis.fullname" . }}
     {{- if .Values.vault.enabled }}
     annotations:
       vault.hashicorp.com/agent-inject: "true"
       vault.hashicorp.com/role: "redis-role"
       vault.hashicorp.com/secret-volume-path: "/secrets"
       vault.hashicorp.com/secret-name: "secret/redis"
     {{- end }}
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: {{ include "redis.fullname" . }}
     template:
       metadata:
         labels:
           app: {{ include "redis.fullname" . }}
       spec:
         containers:
         - name: redis
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
           ports:
           - containerPort: 6379
           {{- if not .Values.vault.enabled }}
           env:
           - name: REDIS_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: {{ include "redis.fullname" . }}-secret
                 key: password
           {{- end }}
           volumeMounts:
           - name: data
             mountPath: /data
           resources: {{ toYaml .Values.resources | nindent 12 }}
           livenessProbe:
             tcpSocket:
               port: 6379
             initialDelaySeconds: 30
             periodSeconds: 10
         volumes:
         - name: data
           persistentVolumeClaim:
             claimName: {{ include "redis.fullname" . }}-pvc