apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  type: NodePort
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
    nodePort: {{ .Values.redis.nodePort }}
  {{- if .Values.exporter.enabled }}
  - name: exporter
    port: {{ .Values.exporter.port }}
    targetPort: {{ .Values.exporter.port }}
    nodePort: {{ .Values.exporter.nodePort }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-redis