mongodb:
  image: mongo:7.0
  port: 27017
  nodePort: 30013
  rootPassword: mongodb-secret
  database: mydb
persistence:
  enabled: true
  storageClass: local-storage
  accessModes:
    - ReadWriteOnce
  size: 8Gi