image:
  repository: gitlab/gitlab-ce
  tag: "17.5.0-ce.0"
  pullPolicy: IfNotPresent

psql:
  host: "127.0.0.1"
  port: 30001
  database: "gitlabhq_production"
  username: "postgres"
  password: "supersecret"

redis:
  host: "127.0.0.1"
  port: 30007
  password: "redis-secret"

minio:
  host: "127.0.0.1"
  port: 30014
  accessKey: "minioadmin"
  secretKey: "minio-secret-key"

global:
  edition: ce
  hosts:
    domain: "gitlab.velesoft.ru"
    https: true
  ingress:
    enabled: true
    class: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
  appConfig:
    objectStorage:
      enabled: true
      bucket: "gitlab-artifacts"
    lfs:
      enabled: true
      bucket: "gitlab-lfs"
    uploads:
      enabled: true
      bucket: "gitlab-uploads"
    packages:
      enabled: true
      bucket: "gitlab-packages"

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "4Gi"

persistence:
  enabled: true
  storageClass: "local-storage"
  size: "20Gi"
  accessModes:
    - ReadWriteOnce

initialRootPassword: "supersecret"

service:
  type: ClusterIP
  port: 80