image:
  repository: gitlab/gitlab-ce
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
global:
  psql:
    host: "{{ .Release.Name }}-postgres"
    port: 5432
    database: "mydb"
    username: "postgres"
    password:
      secret: "{{ .Release.Name }}-postgres-secret"
      key: "password"
  redis:
    host: "{{ .Release.Name }}-redis"
    port: 6379
    password:
      secret: "{{ .Release.Name }}-redis-secret"
      key: "password"
  minio:
    enabled: true
    host: "{{ .Release.Name }}-minio"
    port: 9000
    accessKey:
      secret: "{{ .Release.Name }}-minio-secret"
      key: "accessKey"
    secretKey:
      secret: "{{ .Release.Name }}-minio-secret"
      key: "secretKey"
resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"