postgresql:
  install: false
redis:
  install: false
minio:
  enabled: false

global:
  edition: ce
  hosts:
    domain: "gitlab.velesoft.ru"
    https: true
  ingress:
    enabled: true
    class: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
  psql:
    host: "k8s-main"
    port: 30001
    database: "gitlabhq_production"
    username: "postgres"
    password: "supersecret"
  redis:
    host: "k8s-main"
    port: 30007
    password: "redis-secret"
  minio:
    host: "k8s-main"
    port: 30014
    accessKey: "minioadmin"
    secretKey: "minio-secret-key"
  appConfig:
    objectStorage:
      enabled: true
      connection:
        provider: "AWS"
        endpoint: "http://k8s-main:30014"
        aws_access_key_id: "minioadmin"
        aws_secret_access_key: "minio-secret-key"
        path_style: true
      bucket: "gitlab-artifacts"
    lfs:
      enabled: true
      bucket: "gitlab-lfs"
    uploads:
      enabled: true
      bucket: "gitlab-uploads"
    packages:
      enabled: true
      bucket: "gitlab-packages"

webservice:
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
sidekiq:
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
gitaly:
  persistence:
    enabled: true
    storageClass: "local-storage"
    size: "20Gi"
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"

initialRootPassword: "supersecret"

service:
  type: ClusterIP
  port: 80