# Настройки Grafana
grafana:
  enabled: true
  service:
    type: NodePort
    port: 80
    nodePort: 30004
  adminUser: admin
  adminPassword: grafana-secret  # Измени на свой
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated.default.svc:9090  # Внутренний URL Prometheus
        access: proxy
        isDefault: true
  dashboards:
    default:
      postgresql:
        gnetId: 9628  # Дашборд для PostgreSQL метрик
        revision: 1
        datasource: Prometheus

# Настройки Prometheus
prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30005  # Для доступа к Prometheus UI, если нужно
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        team: frontend  # Или твои лейблы
    additionalScrapeConfigs:
      - job_name: postgres-metrics
        static_configs:
          - targets: ['10.66.66.11:30003']  # Твой NodePort для postgres-metrics
        metrics_path: /metrics

# Node Exporter для метрик сервера
nodeExporter:
  enabled: true
  service:
    type: NodePort
    nodePort: 30006  # Для доступа к Node Exporter, если нужно

# Alertmanager для алертов (опционально)
alertmanager:
  enabled: true

# Kube-State-Metrics для метрик Kubernetes (опционально, но полезно)
kubeStateMetrics:
  enabled: true