apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-{{ .Values.nodeId }}
  labels:
    app: kafka
    nodeId: "{{ .Values.nodeId }}"
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: /mnt/kafka-data-{{ .Values.nodeId }}  # Путь на хосте для локального хранилища
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeName }}  # Укажите имя ноды