# Настройки Zookeeper
zookeeper:
  image: confluentinc/cp-zookeeper:7.5.0
  port: 2181
  nodePort: 30015
  persistence:
    enabled: true
    storageClass: local-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi

# Настройки Kafka
kafka:
  image: confluentinc/cp-kafka:7.5.0
  port: 9092
  nodePort: 30014
  replicas: 1
  nodeIp: "10.66.66.11"  # Замените на реальный IP вашего узла
  zookeeperConnect: "zookeeper:2181"
  persistence:
    enabled: true
    storageClass: local-storage
    accessModes:
      - ReadWriteOnce
    size: 10Gi