image:
  repository: minio/minio
  tag: "RELEASE.2025-09-05T22-47-19Z"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9000
persistence:
  enabled: true
  size: 20Gi
vault:
  enabled: true
resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
minio:
  accessKey: "minioadmin"
  secretKey: "minioadmin"