mysql:
  image: mysql:5.7
  port: 3306
  nodePort: 30009
  rootPassword: mysql-secret
  database: mydb
persistence:
  enabled: true
  storageClass: local-storage
  accessModes:
    - ReadWriteOnce
  size: 8Gi