apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          ports:
            - containerPort: {{ .Values.mariadb.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mariadb.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.mariadb.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb