apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort
  ports:
    - name: mariadb
      port: {{ .Values.mariadb.port }}
      targetPort: {{ .Values.mariadb.port }}
      nodePort: {{ .Values.mariadb.nodePort }}
  selector:
    app: mariadb