postgres:
  replicaCount: 2
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
vault:
  server:
    ha:
      enabled: true
gitlab:
  global:
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"