apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.minio.consolePort }}"
          ports:
            - containerPort: {{ .Values.minio.port }}
              name: minio-api
            - containerPort: {{ .Values.minio.consolePort }}
              name: minio-console
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.accessKey }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.secretKey }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
            - name: config
              mountPath: /root/.minio/config.json
              subPath: config.json
      {{- if .Values.exporter.enabled }}
        - name: minio-exporter
          image: {{ .Values.exporter.image }}
          ports:
            - containerPort: {{ .Values.exporter.port }}
              name: exporter
          env:
            - name: MINIO_URL
              value: "http://localhost:{{ .Values.minio.port }}"
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.accessKey }}
            - name: MINIO_ACCESS_SECRET
              value: {{ .Values.minio.secretKey }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.exporter.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
      {{- end }}
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio
        - name: config
          configMap:
            name: minio