apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9000
    name: api
  - port: 9001
    targetPort: 9001
    name: console
  selector:
    app: {{ include "minio.fullname" . }}