replicas: 1

image: coredns/coredns:1.11.1

ports:
  dns: 53
  dnsNodePort: 30053
  metrics: 9153
  metricsNodePort: 30054
  health: 8080
  ready: 8181

persistence:
  enabled: true
  storageClass: local-storage
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  localPath: /mnt/disks/coredns
  nodeAffinityHostname: k8s-main

resources:
  coredns:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

corefile: |
  .:{{ .Values.ports.dns }} {
      errors
      health :{{ .Values.ports.health }}
      ready :{{ .Values.ports.ready }}
      prometheus 0.0.0.0:{{ .Values.ports.metrics }}
      file /etc/coredns/zones/db.velesoft.ru velesoft.ru
      log
      loop
  }

zoneFiles:
  db.velesoft.ru: |
    $ORIGIN velesoft.ru.
    @ 3600 IN SOA ns1.velesoft.ru. admin.velesoft.ru. (
      2025100601  ; Serial (обновляй при изменениях: YYYYMMDDNN)
      7200         ; Refresh
      3600         ; Retry
      1209600      ; Expire
      3600 )       ; Minimum TTL

    @ 3600 IN NS ns1.velesoft.ru.

    ns1 3600 IN A 37.252.19.157  ; Замени на IP сервиса (kubectl get svc)

    ; Пример записей для твоего домена
    www 3600 IN A 37.252.19.157
    mail 3600 IN MX 10 mail.velesoft.ru.
    mail 3600 IN A 37.252.19.157