apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['localhost:30006']  # NodePort Node Exporter
      - job_name: 'postgres-metrics'
        static_configs:
          - targets: ['10.66.66.11:30003']  # Твой NodePort для PostgreSQL метрик
      - job_name: 'kubernetes'
        static_configs:
          - targets: ['localhost:9090']