apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  type: NodePort
  ports:
  - port: {{ .Values.prometheus.port }}
    targetPort: {{ .Values.prometheus.port }}
    nodePort: {{ .Values.prometheus.nodePort }}
  selector:
    app: prometheus