redis:
  image: redis:7.0
  port: 6379
  nodePort: 30007
  password: redis-secret

exporter:
  enabled: true
  image: oliver006/redis_exporter:latest
  port: 9121
  nodePort: 30008

persistence:
  enabled: true
  storageClass: local-storage
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  localPath: /mnt/disks/redis
  nodeAffinityHostname: k8s-main

resources:
  redis:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  exporter:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"