apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "vault.fullname" . }}-injector
  template:
    metadata:
      labels:
        app: {{ include "vault.fullname" . }}-injector
    spec:
      containers:
      - name: vault-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "agent"
        - "-config=/vault/config/agent.hcl"
        volumeMounts:
        - name: config
          mountPath: /vault/config
      volumes:
      - name: config
        configMap:
          name: {{ include "vault.fullname" . }}-config