apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8200
  selector:
    app: {{ include "vault.fullname" . }}