apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-exporter-config
data:
  .my.cnf: |
    [client]
    user={{ .Values.mysql.username }}
    password={{ .Values.mysql.password }}
    host=localhost
    port={{ .Values.mysql.port }}