apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  my.cnf: |
    [mysqld]
    datadir=/var/lib/mysql
    user=mysql
    bind-address=0.0.0.0
    max_connections=100
    innodb_buffer_pool_size=128M