apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -u
                - {{ .Values.mysql.username }}
                - -p{{ .Values.mysql.password }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -u
                - {{ .Values.mysql.username }}
                - -h
                - localhost
                - -p{{ .Values.mysql.password }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ .Values.resources.mysql | toYaml | nindent 12 }}
      {{- if .Values.exporter.enabled }}
        - name: mysql-exporter
          image: {{ .Values.exporter.image }}
          ports:
            - containerPort: {{ .Values.exporter.port }}
              name: exporter
          env:
            - name: DATA_SOURCE_NAME
              value: "{{ .Values.mysql.username }}:{{ .Values.mysql.password }}@tcp(localhost:{{ .Values.mysql.port }})/{{ .Values.mysql.database }}?parseTime=true&loc=Local"
          volumeMounts:
            - name: exporter-config
              mountPath: /root/.my.cnf
              subPath: .my.cnf
              readOnly: true
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.exporter.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ .Values.resources.exporter | toYaml | nindent 12 }}
      {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql
      {{- else }}
        - name: mysql-data
          emptyDir: {}
      {{- end }}
        - name: exporter-config
          configMap:
            name: mysql-exporter-config