apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        livenessProbe:
          tcpSocket:
            port: {{ .Values.mysql.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.mysql.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
      {{- if .Values.exporter.enabled }}
      - name: mysql-exporter
        image: {{ .Values.exporter.image }}
        ports:
        - containerPort: {{ .Values.exporter.port }}
        env:
        - name: DATA_SOURCE_NAME
          value: "exporter:exporter-secret@tcp(127.0.0.1:{{ .Values.mysql.port }})/"
        livenessProbe:
          httpGet:
            path: /metrics
            port: {{ .Values.exporter.port }}
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: {{ .Values.exporter.port }}
          initialDelaySeconds: 45
          periodSeconds: 5
      {{- end }}
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pvc