apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      nodePort: {{ .Values.service.mysqlNodePort }}
    {{- if .Values.exporter.enabled }}
    - name: exporter
      port: {{ .Values.exporter.port }}
      targetPort: {{ .Values.exporter.port }}
      nodePort: {{ .Values.service.exporterNodePort }}
    {{- end }}
  selector:
    app: mysql