apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  type: NodePort
  ports:
  - name: mysql
    port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
    nodePort: {{ .Values.mysql.nodePort }}
  selector:
    app: {{ .Release.Name }}-mysql